name: Benches

on:
  pull_request:
    paths:
      - ".github/workflows/benches.yml"
      - "benches/**"

jobs:
  benches:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./benches
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - name: Build
        run: RUSTFLAGS=-Dwarnings cargo build --all-targets
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
